name: zavastorefront
metadata:
  template: zava-storefront-appservice-acr

services:
  web:
    project: ../src
    language: dotnet
    host: appservice
    docker:
      path: ../src/Dockerfile

infra:
  provider: bicep
  path: .
